# Generated by Django 4.2.16 on 2024-10-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_desi', models.CharField(max_length=25)),
                ('emp_email', models.EmailField(max_length=50, unique=True)),
                ('emp_mobile', models.CharField(max_length=10, unique=True)),
                ('emp_is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
