# Generated by Django 4.2.16 on 2024-10-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employee_emp_adharno_employee_emp_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_bank_acccount_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_bank_branch_name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_bank_ifsc_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
