# Generated by Django 4.2.16 on 2024-10-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_employee_emp_bank_acccount_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_whatapps_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
