# Generated by Django 4.2.16 on 2024-10-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_employee_emp_whatapps_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acct_id', models.AutoField(primary_key=True, serialize=False)),
                ('acct_code', models.IntegerField()),
                ('acct_name', models.CharField(max_length=45)),
                ('acct_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('acct_pi', models.IntegerField()),
                ('acct_com', models.CharField(blank=True, max_length=60, null=True)),
                ('acct_amt', models.IntegerField()),
                ('acct_startdate', models.DateField()),
                ('acct_enddate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
