# Generated by Django 4.2.16 on 2024-10-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='acct_amt',
            new_name='project_amt',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='acct_code',
            new_name='project_code',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='acct_com',
            new_name='project_com',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='acct_desc',
            new_name='project_desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='acct_enddate',
            new_name='project_enddate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='acct_id',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='acct_name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='acct_pi',
            new_name='project_pi',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='acct_startdate',
            new_name='project_startdate',
        ),
    ]
