# Generated by Django 4.2.16 on 2024-10-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_account_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_com',
            new_name='project_company',
        ),
    ]
