# Generated by Django 4.2.16 on 2024-10-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_project_com_project_project_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=50, unique=True)),
                ('received_date', models.DateField()),
                ('doc_type', models.CharField(choices=[('Imprest', 'Imprest'), ('General', 'General'), ('Administrative', 'Administrative'), ('Scientific', 'Scientific')], max_length=50)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('French', 'French')], max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('received_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.vendor')),
                ('to', models.ManyToManyField(related_name='documents', to='account.employee')),
            ],
        ),
    ]
