# Generated by Django 4.2.16 on 2024-10-24 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_document_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='received_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='account.vendor'),
        ),
    ]
